### ISSUE TITLE
Installer not workin with UwAmp on Windows 10

### ISSUE THREAD

**Issue by ghost** [DiemenDesign/AuroraCMS#1]
Try to setup the CMS, nothing likes to happen when submitting,
meanwile in the dev-tool error is showing. 
What am i doing wrong?

![image](https://user-images.githubusercontent.com/55089955/123506949-2ffcbc00-d667-11eb-9293-39e9bdab98a1.png)
![image](https://user-images.githubusercontent.com/55089955/123506969-486cd680-d667-11eb-8cdd-583c9f390a57.png)

**Comment by ghost** [comment]
After further investigation i found this error:
Parse error: syntax error, unexpected ',' in C:\Users\BLADIBLA\AuroraCMS-0.1.4\core\installer.php on line 34

**Comment by DennisSuitters** [comment]
I've removed that `valid()` jQuery check, which will eventually have been removed anyway, as I'm working on removing jQuery in favour of vanilla Javascript where I can.

Anyway, I've just pushed fixes, which allow the installer to work. I tested it locally in Linux on my local machine, and it works fine. There was also a typo in the installer part, fixed that as well.

**Comment by ghost** [comment]
Great! Thanks, diving into it and checking it out, btw size of master zip is now ~ x10?

**Comment by DennisSuitters** [comment]
Ooops, I accidently added images used for testing when I updated the repo's. Thanks for the heads up, removing those now, and updating the repo.

**Comment by ghost** [comment]
Thanks! Works like a charm now.
