### ISSUE TITLE
Fresh install on WAMP gives manifest.json error 500.

### ISSUE THREAD

**Issue by ghost** [DiemenDesign/AuroraCMS#2]
Got an error while using a fresh install ( on windows with uwamp ) : Error 500 on manifest.json.

![image](https://user-images.githubusercontent.com/55089955/123689040-115b1880-d853-11eb-8e48-760f029cf1d6.png)

![image](https://user-images.githubusercontent.com/55089955/123689697-ce4d7500-d853-11eb-8981-4dbae97a030b.png)

![image](https://user-images.githubusercontent.com/55089955/123689854-fdfc7d00-d853-11eb-845b-efe038526fcd.png)

**Comment by DennisSuitters** [comment]
Ah, yeah, I forgot about that. Will add that to my todo list. Thanks for the heads up.

**Comment by DennisSuitters** [comment]
Had a quick look just now, I got an error as well on this which showed the error being a reference to "bootstrap.min.css", that no longer exists, removed that, and the error has gone. Fix will appear in the next update.

**Comment by ghost** [comment]
Check, thanks.
