### ISSUE TITLE
Settings tab innitial not working in administration.

### ISSUE THREAD

**Issue by ghost** [DiemenDesign/AuroraCMS#3]
While entering administration the settings-tab is not working. It only works if you visite an other tab first.

![image](https://user-images.githubusercontent.com/55089955/123690674-ea054b00-d854-11eb-9089-7f5357edb8a3.png)

**Comment by DennisSuitters** [comment]
What is the # reference in the URL? It's more than likely not matching. I did fix a couple in the last couple of days that I noticed weren't matching.

**Comment by ghost** [comment]
When i'm going into the backend / administration area and click directly on Settings the sub-items are not showing.
It refers to /settings ( not to an #settings ). The "open" class is not appearing on the `<li>`. Only if you click another option first.

**Comment by DennisSuitters** [comment]
I edited you comment so I could see the hidden tags.
I'm not sure what's going on there. I tried to replicate your issue, but it's working fine for me. I tried in Chrome and Firefox in Linux atm.

I just pushed some updates. You will need to update the database as there is additions with this update. I should start doing update packages that contain database changes, and get the update system working.

**Comment by DennisSuitters** [comment]
Oh, you can find the database as `core/aurora.sql`

**Comment by ghost** [comment]
Check, I will do a fresh install from the repo, so i'm sure everything is clean as can be. I'll keep you posted.

**Comment by DennisSuitters** [comment]
No worries, thanks for point out issues.

**Comment by ghost** [comment]
Not working yet, all menu-items with submenu-items load the `**<main></main>**` exept the Settings. Only after clicking first  on another menu item (it does not matter if this menu-item has submenu items or not.)

**Comment by DennisSuitters** [comment]
Are all the "Account Permissions" enabled in the settings tab for the account your signed into, and the rank set to "Administrator" or "Developer"?

**Comment by ghost** [comment]
Hahaha, tested both type whith all permissions on, now i'm adminstrator who couldn't change back to developer ;) I feel a fresh install is comming up.

**Comment by DennisSuitters** [comment]
lol, just edit the row in the database, change table `login` set `rank` to 1000

**Comment by ghost** [comment]
Found something,
in core/layout/sidebar.php  changed line 63 :
FROM:
`echo'<li class="'.($args[0]=='settings'?' open':'').'">'.`
TO:
`echo'<li class="'.($view=='settings'?' open':'').'">'.`

Settings sub-items now showing up.

**Comment by DennisSuitters** [comment]
I made that change and it still worked for me. Strange that with the original `$args[0]` it worked on my system, and not on yours. Regardless, it still works with the your change, so I'll leave it at that.

**Comment by ghost** [comment]
Ok for now ;)
Still got some other strange menu / submenu / viewpane  behaviours, going to setup lamp-machine to test the differences.
