### ISSUE TITLE
Path in summer-note-text-findnreplace.js for css not correct or not working.

### ISSUE THREAD

**Issue by ghost** [DiemenDesign/AuroraCMS#4]
When, for example , editing  Content -> Pages -> Home , the dev-tool gives an 404 on a CSS.
![image](https://user-images.githubusercontent.com/55089955/123691164-8e878d00-d855-11eb-80d2-8e5f868a23f2.png)

**Comment by DennisSuitters** [comment]
hm, I'm not getting that error. I'll see if I can suppress that by moving getting the file out of the script and have it included the same way others are via linking in the head.

**Comment by DennisSuitters** [comment]
Not sure why I wasn't getting an error reported about the file path. Regardless, I've removed the script inclusion of the CSS, and added linking to the CSS file in the meta_head. Should appear in an update soon.

**Comment by ghost** [comment]
Check, thanks!
