### ISSUE TITLE
Opening Media Manager give an error witch can't be clicked away.

### ISSUE THREAD

**Issue by ghost** [DiemenDesign/AuroraCMS#5]
When opening the Media Manager , in this case  Content -> Pages -> Home it gives an error.
![image](https://user-images.githubusercontent.com/55089955/123691741-42891800-d856-11eb-85fa-c33203cf348b.png)

**Comment by DennisSuitters** [comment]
Could you check your allowed permissions in your account settings? Other than that, It's telling us that elfFinder's cofiguration settings are not correct for it to open the folders.

**Comment by ghost** [comment]
Security looks oke, going to fiddle around with elFinder, i'll let you know if i found something. (Looks like a windows thing :)  )
Btw is the media manager going to change when moving from jquery to vanilla js?
![image](https://user-images.githubusercontent.com/55089955/123757258-130df600-d8be-11eb-9e08-cdab9fb63933.png)

**Comment by DennisSuitters** [comment]
The media manage most likely will when removing jQuery from Administration. I've been considering not doing that in the backend, as there's a couple of things that use jQuery like Summernote, and as you know elFinder (plus it uses jQuery-UI).

I don't have a Windows machine to test on atm. Any info you can provide would be awesome.

**Comment by ghost** [comment]
No problemo, just shoot.

**Comment by DennisSuitters** [comment]
OH, just thought of it. Have you checked the read/write permissions of `media/`?

**Comment by ghost** [comment]
Checked that, also tried starting WAMP as administrator, no change jet. Gone ask my friend G. Oogle about Elfinder. I'll be back.

**Comment by ghost** [comment]
This is a hard one... Gues something todo with, elFinder path / os. Keep you posted.

**Comment by DennisSuitters** [comment]
It's for things like this, that I mainly develop in Linux, and due to using Linux hosts, mainly to keep things consistent. I remember there being a weird issue with out directory slash's work between systems.

**Comment by ghost** [comment]
Check, installed an lamp machine and it works like a charm. Simply lovely! Because hosting normaly while be done in a linux-shared-hosting enviroment i will switch from my wamp  to  this lamp machine for development.

**Comment by DennisSuitters** [comment]
Awesome, glad it worked for you.
