### ISSUE TITLE
summernote.js is pointing to .map file / 404 error.

### ISSUE THREAD

**Issue by ghost** [DiemenDesign/AuroraCMS#6]
summernote.js is pointing to .map file whiche give an 404. Removing last line in js-file (link to .map) solves this issue.
When debugging the 404 is showing a lot ;)

**Comment by DennisSuitters** [comment]
Oh, I know what's happened. I'm one of the maintainers for the Summernote project and I'm using the Skunkworks version myself and a couple of others have been working on, I must have built the project locally, placed it into the CMS forgetting to remove the map reference.

**Comment by ghost** [comment]
Check!
