### ISSUE TITLE
Background-color of Live Chat Settings getting gets overruled.

### ISSUE THREAD

**Issue by ghost** [DiemenDesign/AuroraCMS#7]
File 
AuroraCMS/core/js/simplecolorpicker/jquery.simplecolorpicker.css 
gets overruled by
AuroraCMS/core/css/stylesheet-forms.css
`(.btn, button, [role="button"], [type="button"], [type="reset"], [type="submit"] {background-color: var(--button-background-color) !important;})`

![image](https://user-images.githubusercontent.com/55089955/123855905-babc1000-d920-11eb-9881-a15cd4e4d3b1.png)

I gues it should be 
![image](https://user-images.githubusercontent.com/55089955/123856362-4afa5500-d921-11eb-99c7-d7e09562f85a.png)

**Comment by DennisSuitters** [comment]
Yep, should be, you are correct. Thanks for the pickup.

**Comment by DennisSuitters** [comment]
Fixed, I had to `!important` to the script that adds the colours.

**Comment by ghost** [comment]
Check!
